# Generated by Django 4.1.4 on 2022-12-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0004_reflection_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='craving_dh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='cue_dh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='response_dh',
            field=models.BooleanField(default=False),
        ),
    ]
