# Generated by Django 4.1.4 on 2022-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0005_alter_record_craving_dh_alter_record_cue_dh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='best_friend',
            field=models.BooleanField(default='False'),
        ),
    ]
