# Generated by Django 4.1.4 on 2022-12-12 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0006_friend_best_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reflection',
            name='created_at',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reflection',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('current_user', 'friend'), name='unique_friendship'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('date', 'week_reflection'), name='unique_record'),
        ),
        migrations.AddConstraint(
            model_name='reflection',
            constraint=models.UniqueConstraint(fields=('date', 'questionnaire'), name='unique_reflection'),
        ),
    ]
