# Generated by Django 4.1.4 on 2022-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0007_remove_questionnaire_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='name',
            new_name='habit_name',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='start_end',
            new_name='start_today',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='start_habit',
            field=models.BooleanField(default=True),
        ),
    ]
