# Generated by Django 4.1.4 on 2022-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0011_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='filled_in',
            field=models.BooleanField(default=False),
        ),
    ]
