# Generated by Django 4.1.4 on 2022-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0012_record_filled_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='goal_metric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='metric_baseline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reflection',
            name='metric_baseline',
            field=models.IntegerField(default=0),
        ),
    ]
