# Generated by Django 4.1.4 on 2022-12-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0013_record_goal_metric_record_metric_baseline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='goal_metric',
        ),
        migrations.RemoveField(
            model_name='record',
            name='metric_baseline',
        ),
    ]
