# Generated by Django 4.1.4 on 2022-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0014_remove_record_goal_metric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
