# Generated by Django 4.1.4 on 2022-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0015_record_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklog',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
