# Generated by Django 4.1.4 on 2022-12-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0016_weeklog_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklog',
            name='reflection',
        ),
    ]
