# Generated by Django 4.1.4 on 2022-12-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0018_result_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
