# Generated by Django 4.1.4 on 2022-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0019_questionnaire_friday_questionnaire_monday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='notif_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
