# Generated by Django 4.1.4 on 2022-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0022_record_likes_num_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='gif_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
