# Generated by Django 4.1.4 on 2022-12-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0025_alter_friend_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='habit_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='metric_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
