# Generated by Django 4.1.4 on 2023-01-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0026_record_habit_name_record_metric_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='metric_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
