# Generated by Django 4.1.4 on 2023-01-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0028_questionnaire_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='likes_num',
            new_name='comments_num',
        ),
    ]
