# Generated by Django 4.1.4 on 2023-01-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0032_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('record', 'person_liked'), name='unique_like'),
        ),
    ]
