# Generated by Django 4.1.4 on 2023-01-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0035_reflection_start_end'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reflection',
            name='unique_reflection',
        ),
    ]
