# Generated by Django 4.1.4 on 2023-01-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0036_remove_reflection_unique_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
