# Generated by Django 4.1.4 on 2023-01-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neoself', '0038_remove_friend_unique_friendship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.UniqueConstraint(fields=('current_user', 'friend'), name='unique_friendship'),
        ),
    ]
